FROM mcr.microsoft.com/devcontainers/python:3.9-bullseye

# Instalar herramientas adicionales si es necesario
# RUN apt-get update && apt-get install -y <paquetes>

# Establecer directorio de trabajo
WORKDIR /workspace

# Configurar usuario
USER vscode
